### PR TITLE
Create parser for iosxe show ap dot11 dual-band_summary

### LINKED ISSUE #46: 23. show ap dot11 dual-band summary
```
ewlc1# show ap dot11 dual-band summary
AP Name                           Mac Address     Slot  Admin State   Oper State     Width  Txpwr           Mode    Subband    channel 
---------------------------------------------------------------------------------------------------------------------------------------------------------
aa-test-4800                 64d8.14ec.1120  0     Enabled       Down           20     *1/8 (23 dBm)   Local   All        (6)*                     
aa-test-4800                 64d8.14ec.1120  2     Enabled       Down           20     N/A             Monitor All        N/A

```
```
ewlc1# show ap dot11 dual-band summary
AP Name                           Mac Address     Slot  Admin State   Oper State     Width  Txpwr           Mode    Subband    channel 
---------------------------------------------------------------------------------------------------------------------------------------------------------
ad-test-4800                 64d8.1401.40e0  0     Enabled       Down           20     *1/8 (23 dBm)   Local   All        (11)*                    
ad-test-4800                 64d8.1401.40e0  2     Enabled       Down           20     N/A             Monitor All        N/A

```

```
ewlc3# show ap dot11 dual-band summary

```

### PR DESCRIPTION
**Pull request by reustaquio22**

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
submit pr

**Comment by reustaquio22** [comment]
[Cisco PR #217](https://github.com/CiscoTestAutomation/genieparser/pull/217)

**Comment by itdependsnetworks** [comment]
Looks like this feature has been added, can you clean up in issues?

**Comment by itdependsnetworks** [comment]
Completed. https://github.com/CiscoTestAutomation/genieparser/pull/237

**Pull request closed without merging**
