### PR TITLE
Iosxe/show hw module status

### LINKED ISSUE #5: 1 - show hw-module subslot 0/1 transceiver 0 status
```
router>show hw-module subslot 0/1 transceiver 0 status
The Transceiver in slot 0 subslot 1 port 0 is enabled.
  Module temperature                        = +28.750 C
  Transceiver Tx supply voltage             = 3252.5 mVolts
  Transceiver Tx bias current               = 6706 uAmps
  Transceiver Tx power                      = -2.7 dBm
  Transceiver Rx optical power              = -2.1 dBm
router>show hw-module subslot 0/1 transceiver 0 status
The Transceiver in slot 0 subslot 1 port 0 is enabled.
  Module temperature                        = +28.625 C
  Transceiver Tx supply voltage             = 3252.5 mVolts
  Transceiver Tx bias current               = 6706 uAmps
  Transceiver Tx power                      = -2.7 dBm
  Transceiver Rx optical power              = -2.1 dBm
  ```

### PR DESCRIPTION
**Pull request by reustaquio22**

### CODE REVIEW

**Comment by reustaquio22** [comment]
https://github.com/networktocode/genieparser/pull/13
Link to the old PR with a different branch name.

**Review by itdependsnetworks — APPROVED** [review]
Looks good, please submit PR to Cisco repo

**Comment by itdependsnetworks** [comment]
Cisco PR: https://github.com/CiscoTestAutomation/genieparser/pull/196

**Comment by reustaquio22** [comment]
Merged to Cisco Repo

**Pull request closed without merging**
